from langchain_ollama import ChatOllama
from typing import Any, Dict, Optional
import os, json
import logging
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline
from langchain_huggingface import HuggingFacePipeline

logger = logging.getLogger(__name__)

PROMPT = {}

default_master_prompt = "You are a Principal Security Officer. You have been provided with an array of raw security reports generated across multiple individual code modules by our downstream scanning agents.\n\nInput Reports:\n-Reports : {security_agent_reports}\n- Previous Report : {previous_report} // If code is too big it will be chunked and processed one by one. In that case you will get report previously generated by you.\n\nYour task is to immediately compile these disjointed reports into a single, comprehensive Master Security Report. Group the issues logically, identify the single most critical vulnerability across the entire set, and list the components that require immediate intervention. Maintain a completely professional, unembellished tone. Do not include any introductory pleasantries. Do not use emojis."
default_python_prompt = "You are an expert Application Security Engineer. Your job is to perform an security analysis on the provided source code module. \n\nReview the input details below:\n- Code Content: {code}\n- Previous Report : {previous_report} // If code is too big it will be chunked and processed one by one. In that case you will get report previously generated by you.\n\nIdentify any security vulnerabilities, architectural flaws, compliance violations, or insecure coding practices present in the code. For each issue identified, you must specify its location, assess its severity level, explain the underlying risk, and provide a secure code correction. \n\nIf your analysis reveals no security vulnerabilities or weaknesses, explicitly state that the file adheres to secure coding standards. Your response must be direct, technically precise, and strictly professional. No emojis"

environ = os.getenv("ENVIRON","colab")

MODEL_ID = "google/gemma-4-E4B-it"

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    torch_dtype=torch.bfloat16,
    device_map="auto"
)

pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=128000,
    temperature=0.1
)

transformer_llm = HuggingFacePipeline(pipeline=pipe)

ollama_llm = ChatOllama(model="gemma4:latest",temperature=0)

class Config:
    def __init__(self):
        pass
    def _get_prompts(self,technique:str) -> Dict:
        try:
            prompts = None

            with open("./src/prompts/prompts.json") as file:
                prompts = json.loads(file.read())

            PROMPT = prompts[technique] if prompts else {}
        except Exception as e:
            logger.error(e)
            PROMPT = {}
        return PROMPT
    
    def get_prompts(self,technique:str) -> Dict:
        return self._get_prompts(technique=technique)
    
    def get_master_prompt(self)->str:
        return default_master_prompt
    
    def get_python_prompt(self)->str:
        return default_python_prompt

    def get_model(self) -> Any:
        if environ == "colab":
            return transformer_llm
        else:
            return ollama_llm
    
    def get_redis_doc_config(self) -> Any:
        host = os.getenv("REDIS_HOST")
        port = int(os.getenv("REDIS_PORT_DOC","6379"))

        return {"host":host,"port":port}
    
    def get_redis_log_config(self) -> Any:
        host = os.getenv("REDIS_HOST")
        port = int(os.getenv("REDIS_PORT_LOG","6380"))
        return {"host":host,"port":port}

    def get_logs_storage(self) -> Any:
        return os.getenv("LOG_DB","agent_logs.db")