from langchain.agents import create_agent
from src.tools.dir_read import get_relevant_file
from src.config.config import Config
from src.states.app_state import AppState
from src.utils import CacheHandler
from langchain_text_splitters import RecursiveCharacterTextSplitter
from transformers import AutoTokenizer
from langchain_core.messages import message_to_dict
import json, os

config = Config()

cache_handler = CacheHandler()

tokenizer = AutoTokenizer.from_pretrained("google/gemma-4-E4B-it")

def gemma_tokenizer(text:str) -> int:
    return len(tokenizer.encode(text, add_special_tokens=False))

def master_agent(state:AppState) -> AppState:
    print(f"{25*'='}Mater Agent is called{25*'='}\n")
    model = config.get_model()
    agent = create_agent(model=model)

    cache_keys = state["reports"]["docs"]

    context = ""
    results = []

    for key in cache_keys:
        document = cache_handler.get_document(doc_key=key)
        file = document.get("file_path","")
        response = document.get("message","")

        final_response = f"{file}\n{response}\n"
        context += final_response

    splitter = RecursiveCharacterTextSplitter(chunk_size=120000,chunk_overlap=100,length_function=gemma_tokenizer,separators=["\n\n","\n"])

    contexts = splitter.split_text(context)

    for contxt in contexts:
        result = agent.invoke({"messages":[{"role": "user", "content": f"You are a master agent which is executed at the end of operation. You will receive the code reports which are generated by previous agents and you will consolidate entire reports into concise final report. All reports are big we will also provide run it in chunks whre previous responses from master agent are as follows (if it is too big otherwise only one conext): {results}. Current context {contxt}"}]})
        
        messages = result.get("messages", [])

        serializable_messages = [message_to_dict(msg) for msg in messages]

        ai_response = ""
        for msg in serializable_messages:
            if msg["type"]=="ai" and msg["data"]["content"]:
                ai_response = msg["data"]["content"]
                state["reports"]["input_tokens_agent"] += msg["data"]["usage_metadata"]["input_tokens"]
                state["reports"]["output_tokens_agent"] += msg["data"]["usage_metadata"]["output_tokens"]
            elif msg["type"]=="ai" and msg["data"]["tool_calls"]:
                state["reports"]["input_tokens_tool"] += msg["data"]["usage_metadata"]["input_tokens"]
                state["reports"]["output_tokens_tool"] += msg["data"]["usage_metadata"]["output_tokens"]

        results.append(ai_response)
    
    content = f"{results[-1]}\n ## Python Agent Tokens:\n| Field | Value |\n|---|---|\n|Input Token Agent|{state["py_docs"]["input_tokens_agent"]}|\n|Output Token Agent|{state["py_docs"]["output_tokens_agent"]}|\n|Input Token Tool|{state["py_docs"]["input_tokens_tool"]}|\n|Output Token Tool|{state["py_docs"]["output_tokens_tool"]}|\n\n## Master Agent Tokens:\n| Field | Value |\n|---|---|\n|Input Token Agent|{state["reports"]["input_tokens_agent"]}|\n|Output Token Agent|{state["reports"]["output_tokens_agent"]}|\n|Input Token Tool|{state["reports"]["input_tokens_tool"]}|\n|Output Token Tool|{state["reports"]["output_tokens_tool"]}|"
    storage = state["storage_folder"]
    storage = os.path.join(os.path.abspath(storage),"master_report.md")
    with open (storage,"w+",encoding="utf-8") as file:
        file.write(content)
    return state